### ISSUE TITLE
Error when importing cdrouter in Python 3.5

### ISSUE THREAD

**Issue by mbanders** [qacafe/cdrouter.py#5]
Using Python 3.5, just trying to import from cdrouter, I get an error:

```
$ python
Python 3.5.2 (default, Jul 10 2019, 11:58:48) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cdrouter import CDRouter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/local/jenkins/workspace/mytest/venv3/lib/python3.5/site-packages/cdrouter/__init__.py", line 10, in <module>
    from .cdrouter import CDRouter
  File "/local/jenkins/workspace/mytest/venv3/lib/python3.5/site-packages/cdrouter/cdrouter.py", line 33, in <module>
    from .imports import ImportsService
  File "/local/jenkins/workspace/mytest/venv3/lib/python3.5/site-packages/cdrouter/imports.py", line 120, in <module>
    class RequestSchema(Schema):
  File "/local/jenkins/workspace/mytest/venv3/lib/python3.5/site-packages/cdrouter/imports.py", line 123, in RequestSchema
    configs = DictField(fields.Str(), ResourceSchema())
  File "/local/jenkins/workspace/mytest/venv3/lib/python3.5/site-packages/cdrouter/cdr_dictfield.py", line 15, in __init__
    super(DictField, self).__init__(self, *args, **kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
>>> 
```

That import works fine in Python 2.7.

**Comment by nwidger** [comment]
@mbanders Thanks for reporting this issue.  I believe it ultimately stems from the same issue as #4, that being that the version of the Python Marshmallow package installed on your system is not compatible with cdrouter.py.  Would you mind running the `pip install` command referenced in that issue which downgrades Marshmallow back to the latest v2.x.x series and see if that resolves your problem?

**Comment by mattsm** [comment]
@nwidger Is there any chance to add support for the new version of Marshmellow?

**Comment by nwidger** [comment]
@mattsm We would like to, eventually.  The main issue is that the 3.x.x release of Marshmallow dropped support entirely for Python 2, which many users of cdrouter.py are still currently using.

**Comment by mattsm** [comment]
@nwidger ahh, actually we are in a rush to move to python3 at the moment so that's why this was posted here.

**Comment by nwidger** [comment]
@mattsm Gotcha, that makes perfect sense.  The 2.x.x branch of Marshmallow supports both Python2 and 3, so if you want to use cdrouter.py with Python 3 you'll just need to ensure you have the latest 2.x.x version of Marshmallow installed.  Running this command (possibly substituting `pip` for `pip3`) should do that for you:

```
pip install 'marshmallow<3' --force-reinstall
```

**Comment by nwidger** [comment]
This issue should be fixed in cdrouter.py v0.5.5 and newer.  Please feel free to open a new issue if you upgrade and are still having problems.
