### ISSUE TITLE
Python Error report: Syntax Error Options in example case

### ISSUE THREAD

**Issue by avatar8000** [qacafe/cdrouter.py#6]
Hi ,
I follow the https://cdrouterpy.readthedocs.io/en/latest/introduction.html#download-install

But there is error about this line below, It seem something wrong in using Options in Job.

   j = c.jobs.launch(Job(package_id=p.id, Options(extra_cli_args='-testvar myvar=example')))
                                          ^
SyntaxError: positional argument follows keyword argument

Then I delete Options and run again. It seems works. but another error was report. 

    print('    Result-ID: ' + j.result_id)
TypeError: can only concatenate str (not "int") to str

Process finished with exit code 1

Thanks in advance

**Comment by nwidger** [comment]
@avatar8000 Thank you for reporting the errors in the example.  I've just published v0.5.3 of cdrouter.py which should fix the code in the example.  The new code is now shown here as well:

https://cdrouterpy.readthedocs.io/en/latest/introduction.html

Please let me know if the updated example code works for you so we can close out this issue.  Thanks!
